-- V1__init_schema.sql
-- 1. site
CREATE TABLE site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_key VARCHAR(100) NOT NULL UNIQUE,
    site_name VARCHAR(200) NOT NULL,
    idol_name VARCHAR(200) NOT NULL,
    owner_user_id BIGINT,
    visibility VARCHAR(20) NOT NULL DEFAULT 'PUBLIC',
    status VARCHAR(20) NOT NULL DEFAULT 'PUBLISHED',
    is_seeded_site BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_site_owner_user_id ON site(owner_user_id);
CREATE INDEX idx_site_status_visibility ON site(status, visibility);

-- 2. site_theme_setting
CREATE TABLE site_theme_setting (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL UNIQUE,
    primary_color_hex VARCHAR(20),
    secondary_color_hex VARCHAR(20),
    accent_color_hex VARCHAR(20),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_theme_site FOREIGN KEY (site_id) REFERENCES site(id)
);

-- 3. idol_group
CREATE TABLE idol_group (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    group_name VARCHAR(200) NOT NULL,
    group_kana VARCHAR(200),
    official_name VARCHAR(200),
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_group_site FOREIGN KEY (site_id) REFERENCES site(id)
);
CREATE INDEX idx_group_site_id ON idol_group(site_id);

-- 4. member
CREATE TABLE member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    member_name VARCHAR(200) NOT NULL,
    member_name_kana VARCHAR(200),
    birthday DATE,
    member_color VARCHAR(50),
    member_color_hex VARCHAR(20),
    birthplace VARCHAR(100),
    short_bio VARCHAR(500),
    profile_image_url VARCHAR(1000),
    display_order INT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_member_site FOREIGN KEY (site_id) REFERENCES site(id)
);
CREATE INDEX idx_member_site_id ON member(site_id);
CREATE INDEX idx_member_display_order ON member(display_order);
CREATE INDEX idx_member_name ON member(member_name);

-- 5. member_group_history
CREATE TABLE member_group_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    role_type VARCHAR(30) NOT NULL DEFAULT 'MEMBER',
    generation_label VARCHAR(50),
    joined_on DATE,
    left_on DATE,
    is_primary BOOLEAN NOT NULL DEFAULT TRUE,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_mgh_site FOREIGN KEY (site_id) REFERENCES site(id),
    CONSTRAINT fk_mgh_member FOREIGN KEY (member_id) REFERENCES member(id),
    CONSTRAINT fk_mgh_group FOREIGN KEY (group_id) REFERENCES idol_group(id)
);
CREATE INDEX idx_mgh_member_id ON member_group_history(member_id);
CREATE INDEX idx_mgh_group_id ON member_group_history(group_id);
CREATE INDEX idx_mgh_member_period ON member_group_history(member_id, joined_on, left_on);

-- 6. single_release
CREATE TABLE single_release (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    release_type VARCHAR(30) NOT NULL DEFAULT 'SINGLE',
    title VARCHAR(200) NOT NULL,
    title_kana VARCHAR(200),
    release_date DATE,
    catalog_number VARCHAR(100),
    jacket_image_url VARCHAR(1000),
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_single_site FOREIGN KEY (site_id) REFERENCES site(id)
);
CREATE INDEX idx_single_site_id ON single_release(site_id);
CREATE INDEX idx_single_release_date ON single_release(release_date);
CREATE INDEX idx_single_display_order ON single_release(display_order);

-- 7. song
CREATE TABLE song (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    group_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    title_kana VARCHAR(200),
    title_roman VARCHAR(200),
    description VARCHAR(1000),
    has_call_data BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_song_site FOREIGN KEY (site_id) REFERENCES site(id),
    CONSTRAINT fk_song_group FOREIGN KEY (group_id) REFERENCES idol_group(id)
);
CREATE INDEX idx_song_site_id ON song(site_id);
CREATE INDEX idx_song_group_id ON song(group_id);
CREATE INDEX idx_song_title ON song(title);
CREATE INDEX idx_song_title_kana ON song(title_kana);
CREATE INDEX idx_song_site_title ON song(site_id, title);

-- 8. release_song
CREATE TABLE release_song (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    release_id BIGINT NOT NULL,
    song_id BIGINT NOT NULL,
    track_number INT,
    disc_number INT,
    is_primary BOOLEAN NOT NULL DEFAULT FALSE,
    is_title_track BOOLEAN NOT NULL DEFAULT FALSE,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_rs_site FOREIGN KEY (site_id) REFERENCES site(id),
    CONSTRAINT fk_rs_release FOREIGN KEY (release_id) REFERENCES single_release(id),
    CONSTRAINT fk_rs_song FOREIGN KEY (song_id) REFERENCES song(id),
    CONSTRAINT uk_release_song UNIQUE (release_id, song_id)
);
CREATE INDEX idx_release_song_release_id ON release_song(release_id);
CREATE INDEX idx_release_song_song_id ON release_song(song_id);
CREATE INDEX idx_release_song_song_primary ON release_song(song_id, is_primary);

-- 9. song_member
CREATE TABLE song_member (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    song_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    role_type VARCHAR(30) NOT NULL DEFAULT 'ORIGINAL_VOCAL',
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sm_song FOREIGN KEY (song_id) REFERENCES song(id),
    CONSTRAINT fk_sm_member FOREIGN KEY (member_id) REFERENCES member(id),
    CONSTRAINT uk_song_member UNIQUE (song_id, member_id, role_type)
);
CREATE INDEX idx_song_member_song_id ON song_member(song_id);
CREATE INDEX idx_song_member_member_id ON song_member(member_id);

-- 10. song_alias
CREATE TABLE song_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    song_id BIGINT NOT NULL,
    alias_type VARCHAR(30) NOT NULL DEFAULT 'SEARCH',
    alias_text VARCHAR(255) NOT NULL,
    normalized_text VARCHAR(255) NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sa_site FOREIGN KEY (site_id) REFERENCES site(id),
    CONSTRAINT fk_sa_song FOREIGN KEY (song_id) REFERENCES song(id)
);
CREATE INDEX idx_song_alias_song_id ON song_alias(song_id);
CREATE INDEX idx_song_alias_normalized_text ON song_alias(normalized_text);

-- 11. member_alias
CREATE TABLE member_alias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    member_id BIGINT NOT NULL,
    alias_type VARCHAR(30) NOT NULL DEFAULT 'SEARCH',
    alias_text VARCHAR(255) NOT NULL,
    normalized_text VARCHAR(255) NOT NULL,
    display_order INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ma_site FOREIGN KEY (site_id) REFERENCES site(id),
    CONSTRAINT fk_ma_member FOREIGN KEY (member_id) REFERENCES member(id)
);
CREATE INDEX idx_member_alias_member_id ON member_alias(member_id);
CREATE INDEX idx_member_alias_normalized_text ON member_alias(normalized_text);

-- 12. call_type_master
CREATE TABLE call_type_master (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id BIGINT NOT NULL,
    call_type_code VARCHAR(30) NOT NULL,
    call_type_label VARCHAR(100) NOT NULL,
    color_hex VARCHAR(20),
    icon_key VARCHAR(50),
    description VARCHAR(255),
    display_order INT NOT NULL DEFAULT 0,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ctm_site FOREIGN KEY (site_id) REFERENCES site(id),
    CONSTRAINT uk_call_type UNIQUE (site_id, call_type_code),
    CONSTRAINT uk_call_type_code UNIQUE (call_type_code)
);
CREATE INDEX idx_call_type_site_id ON call_type_master(site_id);

-- 13. song_call_block
CREATE TABLE song_call_block (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    song_id BIGINT NOT NULL,
    block_type VARCHAR(30) NOT NULL DEFAULT 'VERSE',
    block_label VARCHAR(50),
    order_no INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_scb_song FOREIGN KEY (song_id) REFERENCES song(id)
);
CREATE INDEX idx_call_block_song_id ON song_call_block(song_id);
CREATE INDEX idx_call_block_order ON song_call_block(song_id, order_no);

-- 14. song_call_line
CREATE TABLE song_call_line (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    block_id BIGINT NOT NULL,
    line_no INT NOT NULL DEFAULT 0,
    lyrics TEXT NOT NULL,
    note VARCHAR(500),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_scl_block FOREIGN KEY (block_id) REFERENCES song_call_block(id),
    CONSTRAINT uk_call_line UNIQUE (block_id, line_no)
);
CREATE INDEX idx_call_line_block_id ON song_call_line(block_id);
CREATE INDEX idx_call_line_block_line ON song_call_line(block_id, line_no);

-- 15. song_call_item
CREATE TABLE song_call_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    call_line_id BIGINT NOT NULL,
    call_type_code VARCHAR(30) NOT NULL,
    call_text VARCHAR(500) NOT NULL,
    style_color_hex VARCHAR(20),
    order_no INT NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_sci_line FOREIGN KEY (call_line_id) REFERENCES song_call_line(id),
    CONSTRAINT fk_sci_call_type FOREIGN KEY (call_type_code) REFERENCES call_type_master(call_type_code)
);
CREATE INDEX idx_call_item_line_id ON song_call_item(call_line_id);
CREATE INDEX idx_call_item_type ON song_call_item(call_type_code);
CREATE INDEX idx_call_item_line_order ON song_call_item(call_line_id, order_no);
