import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
    title: 'Next.js Boilerplate',
    description: 'Generated by creating a Next.js application',
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="ja">
            <body>{children}</body>
        </html>
    );
}
